# Default values for celery-flower.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
celery_flower:
  secrets:
    data:
      flower_credentials:
        FLOWER_BROKER_API: # from dependency
        CELERY_BROKER_URL: # from dependency 

replicaCount: 1

image:
  repository: mher/flower
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5555

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
