# Default values for celery-flower.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rabbitmq:
  host: # from dependency
  port: 5672
  user: celery_broker_user
  vhost: api

secrets:
  CELERY_BROKER_PASSWORD: # from dependency

replicaCount: 1

image:
  repository: mher/flower
  pullPolicy: Always
  tag: "2.0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

containerPort: 5555

ports:
  - containerPort: 5555
    name: http
    protocol: TCP

service:
  ports:
    - port: 5555
      targetPort: http
      protocol: TCP
      name: http
  type: LoadBalancer
  loadBalancerIP: # from dependency
  annotations:
    networking.gke.io/load-balancer-type: Internal

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
