# Default values for celery-flower.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rabbitmq:
  host: service-broker-rabbitmq
  port: 5672
  user: celery_broker_user
  vhost: api

secrets:
  celery-credentials:
    CELERY_BROKER_PASSWORD: # from dependency

replicaCount: 1

image:
  repository: mher/flower
  pullPolicy: Always
  tag: "2.0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5555

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
