# Default values for clusterissuer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  groupName: ""

dnsSolverApplicationKey: ""
dnsSolverApplicationSecret: ""
dnsSolverConsumerKey: ""
httpSolverEnabled: true
dnsSolverEnabled: false

certIssuer:
  nameOverride: ""
  fullnameOverride: ""
  email: "vincent.dudek@nw-groupe.com" # This is a required field if create == true
  name: lets-encrypt-http-issuer-production
  secretName: letsencrypt-credentials
  server: https://acme-v02.api.letsencrypt.org/directory
  httpResolver:
    ingressClass: traefik
    ingressTemplate:
      metadata:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
          traefik.ingress.kubernetes.io/router.priority: "1024"

cert-manager-webhook-ovh:
  nameOverride: "cert-manager-webhook-ovh"
  fullnameOverride: "cert-manager-webhook-ovh"
