{{- if .Values.dnsSolverEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ovh-credentials
  namespace: cert-manager
type: Opaque
data:
  applicationSecret: {{ .Values.dnsSolverApplicationSecret | b64enc | quote }}
{{- end }}