{{- range .Values.poolers }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: {{ include "cluster.fullname" $  }}-pooler-{{ .name }}
  namespace: {{ include "cluster.namespace" $ }}
spec:
  cluster:
    name: {{ include "cluster.fullname" $ }}
  instances: {{ .instances }}
  type: {{ default "rw" .type }}
  pgbouncer:
    poolMode: {{ default "session" .poolMode }}
    {{- with .authQuerySecret }}
    authQuerySecret:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .authQuery }}
    authQuery:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .parameters }}
    parameters:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .pg_hba }}
    pg_hba:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{ with .monitoring }}
  monitoring:
  {{- if not (empty .podMonitor) }}
    enablePodMonitor: {{ and .enabled .podMonitor.enabled }}
    {{- with .podMonitor.relabelings }}
    podMonitorRelabelings:
      {{- toYaml . | nindent 6 }}
    {{ end }}
    {{- with .podMonitor.metricRelabelings }}
    podMonitorMetricRelabelings:
      {{- toYaml . | nindent 6 }}
    {{ end }}
  {{- end }}
  {{- end }}
  {{- $pa := .podAntiAffinity | default dict }}
  {{- if .template }}
  template:
    {{- .template | toYaml | nindent 4 }}
  {{- else if $pa.enabled }}
  template:
    spec:
      affinity:
        podAntiAffinity:
          {{- if eq ($pa.podAntiAffinityType | default "preferred") "required" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: {{ $pa.topologyKey | default "kubernetes.io/hostname" }}
              labelSelector:
                matchLabels:
                  cnpg.io/poolerName: {{ include "cluster.fullname" $ }}-pooler-{{ .name }}
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: {{ $pa.topologyKey | default "kubernetes.io/hostname" }}
                labelSelector:
                  matchLabels:
                    cnpg.io/poolerName: {{ include "cluster.fullname" $ }}-pooler-{{ .name }}
          {{- end }}
  {{- end }}
  {{- with .serviceTemplate }}
  serviceTemplate:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
