
image:
  repository: gke.gcr.io/ip-masq-agent
  pullPolicy: IfNotPresent
  tag: "v2.12.0-gke.8"

imagePullSecrets: []
# This is to override the chart name.
nameOverride: "ip-masq-agent"
fullnameOverride: "ip-masq-agent"

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}


# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

tolerations: 
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - key: "CriticalAddonsOnly"
    operator: "Exists"


configMap:
  data:
    nonMasqueradeCIDRs:
      - 0.0.0.0/0
    masqLinkLocal: true
    resyncInterval: 60s