
{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "celery-flower.name" $ }}-flower-credentials
stringData:
  FLOWER_BROKER_API: {{ .Values.secrets.data.FLOWER_BROKER_API }}
  CELERY_BROKER_URL: {{ .Values.secrets.data.CELERY_BROKER_URL }}
{{- end -}}
