apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "celery-flower.name" $ }}-flower-credentials"
stringData:
  FLOWER_BROKER_API: "http://{{ .Values.rabbitmq.user }}:{{ .Values.secrets.CELERY_BROKER_PASSWORD }}@{{ .Values.rabbitmq.host }}:{{ .Values.rabbitmq.port }}/{{ .Values.rabbitmq.vhost }}/"
  CELERY_BROKER_URL: "amqp://{{ .Values.rabbitmq.user }}:{{ .Values.secrets.CELERY_BROKER_PASSWORD }}@{{ .Values.rabbitmq.host }}:{{ .Values.rabbitmq.port }}"