
{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "celery-flower.name" $ }}-flower-credentials
stringData:
  FLOWER_BROKER_API: 'http://{{ .Values.configMap.data.CELERY_BROKER_USER }}:{{ (index .Values.secrets.data "celery-credentials").CELERY_BROKER_PASSWORD }}@market-access-rabbitmq:5672/api/'
  CELERY_BACKEND_URL: 'db+postgresql+psycopg2://{{ .Values.configMap.data.CELERY_BACKEND_USER }}:{{ (index .Values.secrets.data "celery-credentials").CELERY_BACKEND_PASSWORD }}@{{ .Values.configMap.data.CELERY_DB_HOST }}/{{ .Values.configMap.data.CELERY_BACKEND_DB }}'
  CELERY_BROKER_URL: 'amqp://{{ .Values.configMap.data.CELERY_BROKER_USER }}:{{ (index .Values.secrets.data "celery-credentials").CELERY_BROKER_PASSWORD }}@market-access-rabbitmq:5672'
{{- end -}}
