apiVersion: v1
kind: Secret
metadata:
  name: {{ include "celery-flower.name" $ }}-flower-credentials
stringData:
  FLOWER_BROKER_API: {{ .Values.celery_flower.secrets.flower_credentials.FLOWER_BROKER_API }}
  CELERY_BROKER_URL: {{ .Values.celery_flower.secrets.flower_credentials.CELERY_BROKER_URL }}