apiVersion: v1
kind: Service
metadata:
  name: {{ include "celery-flower.fullname" . }}
  labels:
    {{- include "celery-flower.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    {{- include "celery-flower.selectorLabels" . | nindent 4 }}
