
{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "celery-worker.name" $ }}-celery-urls
stringData:
  CELERY_BACKEND_URL: 'db+postgresql+psycopg2://{{ .Values.configMap.data.CELERY_BACKEND_USER }}:{{ (index .Values.secrets.data "celery-credentials").CELERY_BACKEND_PASSWORD }}@{{ .Values.configMap.data.CELERY_DB_HOST }}/{{ .Values.configMap.data.CELERY_BACKEND_DB }}'
  CELERY_BROKER_URL: 'amqp://{{ .Values.configMap.data.CELERY_BROKER_USER }}:{{ (index .Values.secrets.data "celery-credentials").CELERY_BROKER_PASSWORD }}@{{ .Values.configMap.data.CELERY_BROKER_HOST }}:5672'
{{- end -}}
