{{- if .Values.postgresRolesSecrets.enabled -}}
{{- range $current_secret_name, $current_secret := .Values.postgresRolesSecrets.data }}
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ $current_secret_name }}
  labels:
    {{- include "celery-worker.labels" $ | nindent 4 }}
    cnpg.io/reload: "true"
data:
    {{- range $key, $val := $current_secret }}
    {{- print $key | nindent 2 }}: {{ print $val | b64enc | quote -}}
    {{ end }}

---
{{ end }}
{{- end -}}
