{{- range $worker_name, $worker := .Values.workers.workers }}
{{- if $worker.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "celery-worker.fullname" $ }}-{{ $worker_name }}
  labels:
    {{- include "celery-worker.labels" $ | nindent 4 }}
spec:
  {{- if not $.Values.workers.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "celery-worker.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "celery-worker.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "celery-worker.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "celery-worker.fullname" $ }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - {{ include "celery-worker.command" (dict "worker" $worker "Values" $.Values) }}
          envFrom:  
            - configMapRef:
                name: {{ include "celery-worker.fullname" $ }}-configmap
            - secretRef:
                name: {{ include "celery-worker.fullname" $ }}-celery-urls
            {{- if $.Values.secrets.enabled }}
            {{- range $secretName, $_ := $.Values.secrets.data }}
            - secretRef:
                name: {{ include "celery-worker.fullname" $ }}-{{ $secretName }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- range $probeType := (list "readiness" "liveness") }}
          {{ $probeType }}Probe:
            {{- include "celery-worker.probe" (dict "workerType" $worker.type "probeType" $probeType "Values" $.Values) | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $worker.resources | nindent 12 }}
      {{- with $worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

{{- end -}}
{{- end -}}
